doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            user_id:
                class: App\Identity\Infrastructure\Persistence\Type\UserIdType
            email_vo:
                class: App\Identity\Infrastructure\Persistence\Type\EmailType
            username_vo:
                class: App\Identity\Infrastructure\Persistence\Type\UsernameType
            hashed_password:
                class: App\Identity\Infrastructure\Persistence\Type\HashedPasswordType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Identity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Identity/Infrastructure/Persistence/Mapping'
                prefix: 'App\Identity\Domain\Model'
                alias: Identity
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
