framework:
    messenger:
        buses:
            messenger.bus.default:
                default_middleware:
                    allow_no_handlers: true

        transports:
            sync: 'sync://'

        routing:
            App\Identity\Domain\Event\UserRegistered: sync
            App\Identity\Domain\Event\UserEmailChanged: sync
            App\Identity\Domain\Event\UserPasswordChanged: sync
