# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

shared_controllers:
    resource: ../src/Shared/Presentation/Controller/
    type: attribute

identity_controllers:
    resource: ../src/Identity/Presentation/Controller/
    type: attribute
